[package]
name = "spring_challenge_2021"
version = "0.1.0"
authors = ["Nicolas Delsaux <nicolas.delsaux@gmx.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
spectral = "0.6"