[package]
name = "spring-challenge"
version = "0.1.0"
authors = ["Nicolas Delsaux <nicolas.delsaux@gmx.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
