== Les règles

Là, c'est simple, ce sont les règles classiques du bomberman. Et par classique, je veux dire vraiment classique (rien à voir avec [XBlast](https://fr.wikipedia.org/wiki/XBlast?oldformat=true), par exemple). On a donc

* des caisses (explosables qui amènent des bonus)
* des murs (non explosable)
* des bonus de deux type : une bombe de plus, une portée de bombe plus grande
* Et bien sûr, des joueurs ennemis à détruire

== Le plan

Au début, je n'en avais pas vraiment. Je suis donc parti dans une veine assez TDD : j'écris un test, j'implémente ce qu'il faut, et je refactore une. ca m'a donc mené à ma première implémentation.

== L'épopée du chasseur-tueur

=== Concept
Conceptuellement, bomberman est assez simple et peut se résumer en quelques points-clé

* Trouver la bombe la plus proche
* Poser une bombe sur la case à côté
* Eviter la zone d'explosion (mais ça ne concerne pas les zones wood, donc je n'en ai pas tenu compte ici)
* Trouver le bonus le plus proche

Et gagner !

=== Implémentation
==== Vu de loin
Dans le deux cas, il faut trouver le truc le plus proche ... selon la http://fr.wikipedia.org/wiki/Distance_de_Manhattan[Distance de Manhattan]. Il me faut donc

* Une carte fidèle du terrain
* Une représentation des différents types de contenu
* De quoi placer les bombes (parce que les bombes placées suppriment les boîtes).
* Et de quoi stocker le contenu

==== Comment faire tout ça ?

Maintenant que j'ai fait quelques problèmes Codingame en différents langages, la question du langage à choisir se pose. J'ai essayé quelques langages. Mais franchement, le seul que je puisse prétendre maîtriser, et pour lequel je dispose de l'outillage adapté à un challenge comme Hypersonic, c'est Java.

Donc un projet Java/Maven/JUnit, et ça ira !

Passons maintenant au code. Là, aussi, ça va assez vite.

[uml,file="hunter-killer-classes.png"]
--
enum Content {
		NOTHING
		BOX
		WALL
		FIRE
}
enum Actions {
    MOVE
    BOMB
}
class Playground
Playground : int width
Playground : int height

Playground "1" *-- "*" Content : [][]positions

class Entity
Entity : int x
Entity : int y
Entity<|--Location
Location : Content content
Entity<|--GameEntity
GameEntity : int id
GameEntity : int param1
GameEntity : int param2
GameEntity<|--Item
GameEntity<|--Bomb
GameEntity<|--Bomber
--

Tout ça permet une exécution assez simple
[uml,file="hunter-killer-sequence.png"]
--
Player->Bomber:attackNearestBomb\n(playground, droppedBombs, items)
loop pour toutes les bombes
    Bomber->Bomb:clearPlayground\n(playground)
    note left
        Remplace le contenu de toutes les cases
        par Content.NOTHING
    end note
end
Bomber->Playground:sortByDistanceTo(Content.BOX, this, 2)
note left
Retourne les deux boîtes
les plus proches
end note
alt Il reste des boîtes
    alt Il y a des items plus proches
        Bomber->Item:perform(Actions.MOVE)
    else
        alt On peut poser une bombe
            Bomber->Bomb:perform(Actions.BOMB)
        else
            Bomber->Bomb:perform(Actions.MOVE)
        end
    end
end
--

Avec cette version, j'ai quand même réussi, après quelques optimisations, à atteindre le bronze. Mais là, tout s'écroulait : comme les bombes devenaient dangereuses, il me fallait les éviter à temps.

== Le chasseur-tueur voit l'avenir

=== Concept
Comme j'avais déja une carte des positions, je me suis dit qu'il serait assez facile de la transforme en une carte du futur : pour chaque instant de la simulation, on sait où sont les bombes, quand elles explosent, la portée de leur explosion, les réactions en chaîne, ...

=== Echec critique

Je me suis donc mis à modifier mon code pour intégrer tout ça. Hélas, après trois jours de travail, j'ai compris que c'était une mauvaise idée : je n'arrivais pas à faire rentrer la dimension temps dans ce modèle. Pour être plus précis, je n'arrivais jamais à avoir une simulation correcte des bombes : elles n'explosaient pas vraiment au bonn moment, les explosions en chaine étaient incertaines, et je me mettais trop facilement en danger. Et ça n'était pas faute de disposer de tests, puisque j'en avais pour à peu près tous les cas. Qui plus est, j'avais déja remplacé mon chasseur-tueur par une variante de Monte-Carlo (mais j'y reviendrai plus bas).

J'ai donc utilisé une des méthodes les plus communes en informatique : tout balancer pour pouvoir refaire les mêmes erreurs dans une nouvelle base de code.

== Le chasseur possible

=== Concept

Suite à mes discussions avec un collègue bien meilleur que moi à ce jeu, je me suis intéressé à la méthode de Monte-Carlo. Ma compréhension de cette méthode est la suivante : face à un problème de choix, plutôt que de faire des grandes théories, on tire des solutions au sort, on les score, et on joue la meilleure. Je n'ai pas voulu en comprendre plus pour l'instant, et j'étais initialement raisonablement certain de tenir un truc malin. Cette méthode a toute fois deux prérequis

1. Il faut une simulation correcte de l'espace du problème
1. Il faut tester autant de solutions que possible

=== Implémentation

Suite à mes échecs précédents, j'avais donc une idée très fine de ce qu'impliquait Bombermance qui m'a amené à une implémentation basée sur ... les visiteurs ! Oui, on peut faire du design pattern comme un dingue même pour un problème comme celui-là.

[NOTE]
====
Pour information, c'est cette version qui est disponible dans ce repository.
====

J'avais donc les classes suivantes

[uml,file="possible-hunter-classes.png"]
--
enum CanFire {
		NOT,
		END_PROPAGATION,
		YES
}
enum Action {
    MOVE, 
    BOMB
}
interface Content
Content<|--Nothing
Content<|--BombDanger
Content<|--Box
Content<|--Wall
Content<|--Fire
Content<|--FireThenItem
Content<|--Entity
Entity : int x
Entity : int y
Entity<|--Bomb
Bomb : int delay
Bomb : int range
Entity<|--Gamer
Gamer : int id
Gamer : int bombs
Gamer : int range
Entity<|--Item
Item : int type
Entity <|-- Step
Step : int score
Step "1" *-- "1" Playground : playground
Step "1" *-- "1" Entity : current
Step "1" *-- "1" Action : action
Step "1" *-- "1" Gamer : gamer
class Playground {
    int width
    int height
}
Playground "1" *-- "*" Content : [][]positions
interface PlaygroundVisitor<Type> {
		void startVisit(Playground playground);
		void startVisitRow(int y);
		void endVisitRow(int y);
		Type endVisit(Playground playground);
		void visit(int x, int y, Content content);
}
interface ContentVisitor<Type> {
		Type visitNothing(Nothing nothing);
		Type visitBox(Box box);
		Type visitWall(Wall wall);
		Type visitGamer(Gamer gamer);
		Type visitBomb(Bomb bomb);
		Type visitItem(Item item);
		Type visitFire(Fire fire);
		Type visitFireThenItem(FireThenItem fireThenItem);
		Type visitBombDanger(BombDanger bombDanger);
	}
class Trajectory {
    int score
}
Trajectory "1" *-- "*" Step : steps
--

Qu'est-ce qu'on fait avec tout ça ?

==== Une vision à jour du terrain

Eh bien c'est assez simple : on visite le `Playground` pour construire sa version suivante, ce qui permet facilement, pour chaque action possible, d'obtenir un état fiable du `Playground` après cette action. Ca, je l'ai testé et re-testé, et ça marche très bien.

Autrement dit, j'ai créé une classe `PlaygroundDeriver` qui, visite le `Playground` à l'instant n (je l'appelle `current`) pour générer celui de l'instant n+1 (je l'appelle `derived`). Pour chaque position `(x,y)`, ce `PlaygroundDeriver` visite le contenu et effectue les opérations suivantes

===== Les cas simples
* Si `current(x,y)` contient `Nothing` , et que `derived(x,y)` ne contient ni ` Fire`, ni `FireThenItem`, je met `Nothing` dans `derived(x,y)`.
* Si `current(x,y)` contient `BombDanger` , et que `derived(x,y)` ne contient pas ` Fire`, je met `BombDanger` dans `derived(x,y)`.
* Si `current(x,y)` contient `Box` , et que `derived(x,y)` ne contient ni ` Fire`, ni `FireThenItem`, je met `Box` dans `derived(x,y)`. Dans le cas contraire, je mets `FireThenItem`
* Si `current(x,y)` contient `Wall` , je mets `Wall` dans `derived(x,y)`.
* Si `current(x,y)` contient `Gamer` , je mets `Gamer` dans `derived(x,y)`. Autrement dit, les ennemis ne bougent pas, et ne meurent pas.
* Si `current(x,y)` contient `Item` , et que `derived(x,y)` ne contient ni ` Fire`, ni `FireThenItem`, je met `Item` dans `derived(x,y)`. Dans le cas contraire, je mets `Fire`, ce qui aura pour effet de supprimer le bonus au tour suivant.
* Si `current(x,y)` contient `Fire` , je mets `Nothing` dans `derived(x,y)`.
* Si `current(x,y)` contient `FireThenItem` , je mets `Item` dans `derived(x,y)`.
* Si `current(x,y)` contient `Bomb` , c'est chaud

===== Ca fait quoi une bombe ?
Avant l'explosion, je place ` BombDanger` autour de l'explosion, et une nouvelle bombe avec un `delay` réduit de 1. Evidement, si il y a `Fire` à l'emplacement de la bombe, j'y mets le feu en appelant la méthode `fireBomb`. De la même manière, quand le délai passe à 0, je remplace la bombe et tous les `BombDanger` par des `Fire`.

===== Et ça marche ?
Suffisement pour que les tests de `PlayerTest` soient toujours au vert.

==== Des trajectoires

Une fois qu'on a ça, on peut construire facilement des trajectoires ... Et malheureusement, c'est là que ça se corse.

L'aglorithme est là aussi redoutablement simple : tant que j'ai le temps, je crée des trajectoires, je les évalue (je calcule leur score, autrement dit), et, si ce score est le meilleur, je prends cette trajectoire. Et au coup suivant, j'oublie tout et je recommence.

=== Ca n'a pas marché ?

Non, ça n'a pas marché ... du tout. Je crois même que le chasseur tueur qui n'évaluait même pas le danger des bombes était pendant longtemps (et peut-être encore aujourd'hui) meilleur que le chasseur possible. Pourquoi ? plusieurs raisons à ça

==== Les performances
Il y avait plusieurs soucis de performance intrinsèques que j'ai pu régler assez facilement à coups de jvisualvm. ca m'a amené à une performance en pic (quand les serveurs de CodinGame étaient peu chargés) d'à peu près 2000 trajectoires évaluées par tour de jeu (avec une profondeur de calcul de 16 coups). C'était bien, mais nettement trop faible pour une stratégie de ce type, surtout une stratégie sans mémoire.

Le problème, c'est que la charge des serveurs CodinGame variait. J'ai alors dû ajouter ce bout de code diabolique

			if(trajectoryBuilder.count<constants.COUNT_ENOUGH_TRAJECTORIES) {
				System.err.println("There was not enough trajectories computed .. Computing even less next turn");
				constants.COUNT_ENOUGH_TRAJECTORIES = Math.max(100, 
						Math.min(constants.COUNT_ENOUGH_TRAJECTORIES, trajectoryBuilder.count/constants.ADAPATION_FACTOR));
			} else {
				if(delay.howLong()<constants.DELAY_CREATE_TRAJECTORIES/2) {
					System.err.println("We computed that really fast. Computing more");
					constants.COUNT_ENOUGH_TRAJECTORIES = Math.min(MAXIMUM_TRAJECTORIES, 
							constants.COUNT_ENOUGH_TRAJECTORIES*constants.ADAPATION_FACTOR);
				}
			}

Si vous ne savez pas lire le Java, et que les commentaires écrits dans `System.err` ne suffisent pas, ce code vérifie le nombre de trajectoires évaluées. Si il est au maximum local, mais inférieur au maximum global, c'est que j'ai pu tout évaluer. Donc j'en évalue plus la prochaine fois. En revanche, si je n'ai pas pu atteindre le maximum, c'est que la VM est chargée. Donc je diminue encore ce nombre. Et malgré ça, malgré ça, même hier après-midi, **j'avais des tonnes de timeout**.

==== Les trajectoires pourries
Au-delà de ça, malgré deux astuces bien choisies (donner un mauvais score aux trajectoires finissant dans des culs-de-sac, et ajouter les `BombDanger` pour éviter que le bot ne reste dans des coins dangeureux), je n'ai jamais réussi à éviter les suicides idiot dont le scénario paradigmal est simple : 

1. le bot pose une bombe à une intersection
1. Il se place dans le cul-de-sac le plus proche
1. La partie est finie, et j'ai perdu

== Conclusion
Une conclusion en plusieurs points.

=== L'hubris a encore frappé !
Je me suis cru fort, et je finis quasi-dernier en bronze. Il y a donc 3000 développeurs bien meilleurs que moi. Bravo à eux.

=== N'utilise pas une tronçoneuse quand tu ne sais pas t'en servir, tu peux y laisser des doigts. 
A mon avis, j'ai sorti Monte-Carlo sans vraiment connaître la méthode, ses impacts ou ses prérequis. Du coup, mon choix de trajectoire était souvent médiocre, parfois carrément suicidaire, et je n'ai pas réussi à corriger le tir parce que j'étais incapable d'appréhender la correction nécessaire.

=== Il vaut mieux adapter une solution qui marche à moitié, que de refaire des erreurs de zéro.
Aujourd'hui, à froid, je suis à peu près certain qu'en adaptant ma stratégie de chasseur-tueur à mon terrain intégrant une prédiction des événements, j'aurais un robot capable de passer le bronze. Du coup, pour la prochaine fois, j'aurais intérêt à trouver la bonne forme de code, sans pour autant sacrifier ce qui fait le succès de la chose.

=== Un emplâtre sur une jambe de bois
J'ai passé pas mal de temps ce week-end à tenter de mettre en place un `Evolver` capable de trouver les bonnes valeurs pour tous les coefficients de score. Mais je n'ai pas non plus réussi à l'implémenter correctement, sans même me douter que le mal était plus profond. La prochaine fois que je développe un outil pour corriger un autre outil, j'y repenserai ... et je m'arrêterai plus vite de faire des bêtises, j'espère.